theme:          jekyll-theme-slate

# Setup
title:          Dissenting Opinion
description:    A Personal Blog for Steven Bosnick

# About / Contact
author:
    name:       Steven Bosnick
    email:      sbosnick@sympatico.ca

